src/vaadin-crud-form.html
src/vaadin-crud-grid.html
src/vaadin-crud.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/27)

Fix height in FF, IE and Edge

---

bower.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/28)

Fix license URLs in package and bower

---

bower.json
src/vaadin-crud.html
test/crud-test.html
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/23)

Use vaadin-confirm-dialog

---

src/vaadin-crud.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/30)

Do not raise exception if path is not set

---

bower.json
src/vaadin-crud.html

Fixes #21
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/35)

Add license checker

---

.travis.yml
src/vaadin-crud-form.html
src/vaadin-crud-grid.html
test/.eslintrc.json
test/crud-form-test.html
test/crud-grid-test.html
test/crud-test.html
test/test-suites.js
wct.conf.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/31)

Unit tests

---

src/vaadin-crud-grid-edit-column.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/56)

Move edit event to vaadin-crud-grid-edit

---

src/vaadin-crud.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/57)

make more specific selector [skip ci]

---

bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/79)

Freeze grid version until #78 is fixed

---

demo/crud-advanced-demos.html
demo/crud-basic-demos.html
demo/crud-custom-demos.html
demo/crud-data-demos.html
demo/crud-i18n-demos.html
demo/demos.json
src/vaadin-crud.html
test/crud-test.html

Inspired in `i18n` solution for other components like upload
Fixes #38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/77)

Localize component

---

demo/crud-advanced-demos.html
src/vaadin-crud.html
src/vaadin-dialog-layout.html
test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/85)

propagate theme to generated components.

---

src/vaadin-crud.html
test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/83)

Set dirty also with `input` events.

---

demo/index.html
src/vaadin-crud.html
test/crud-test.html
theme/lumo/vaadin-crud-styles.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/84)

Adjust dialog styles. 

---

bower.json

Fixes #78
This reverts commit 5d697614d0730acc56e9b66bdfc64a727a5cd077.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/87)

Use latest grid with the extension issue fixed

---

demo/crud-i18n-demos.html
src/vaadin-crud.html
test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/90)

Avoid Java keywords in i18n object property keys

---

demo/crud-advanced-demos.html
demo/crud-custom-demos.html
src/vaadin-crud-edit-column.html
src/vaadin-crud-grid.html
src/vaadin-crud.html
test/crud-grid-test.html
test/crud-test.html
test/visual/default.html
theme/lumo/vaadin-crud-styles.html

Fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/89)

API changes

---

demo/crud-advanced-demos.html

Fixes #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/91)

use grid simple column features in demos (#69)

---

demo/crud-basic-demos.html
demo/crud-custom-demos.html
src/vaadin-crud-form.html
src/vaadin-crud-grid.html
src/vaadin-crud.html
test/crud-form-test.html
test/crud-grid-test.html
test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/88)

Implement include property

---

src/vaadin-crud.html

Fixes #95
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/99)

Fix typo after renaming item. (#95)

---

README.md
vaadin-directory-description.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/100)

Add directory description

---

demo/crud-i18n-demos.html
src/vaadin-crud-edit-column.html
src/vaadin-crud.html
test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/103)

Rename some i18n properties

---

src/vaadin-crud.html

Fixes #105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/107)

Fix initialisation of i18n property

---

.gitignore
src/vaadin-crud.html
test/crud-test.html

Fixes #106
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/108)

Cache items structure

---

bower.json
theme/lumo/vaadin-crud-styles.html
theme/vaadin-dialog-layout-overlay-styles.html

Fixes #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/111)

Fix dialog overlay style

---

demo/crud-advanced-demos.html

Fixes #62
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/114)

highlight search matches in grid

---

demo/crud-data-demos.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/115)

Move significant code to top in demo (#72) [skip ci]

---

src/vaadin-crud.html

The title should pose a question and the confirm button should answer that.
The dismiss button should by default be “Cancel” to be consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/123)

Clarify the dialog messages

---

theme/lumo/vaadin-crud-styles.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/122)

Remove Lumo dialog workaround

---

src/vaadin-crud-edit-column.html
src/vaadin-crud.html
src/vaadin-dialog-layout.html
theme/vaadin-dialog-layout-overlay-styles.html

Fixes #118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/131)

Remove `vaadin-dialog-layout` from API page (#118)

---

src/vaadin-crud.html

Fixes #132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/134)

Fix exclude in forms (#132)

---

test/crud-grid-test.html
test/crud-test.html
test/index.html

Fixes #32
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/135)

Remove shadydom tests

---

demo/crud-custom-demos.html
src/vaadin-crud.html
theme/lumo/vaadin-crud-styles.html
theme/material/vaadin-crud-styles.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/133)

Do not revert toolbar order

---

.travis.yml
src/vaadin-crud.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/138)

Ignore polymer linter exit status

---

bower.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/139)

Use stable confirm-dialog

---

src/vaadin-crud-form.html
src/vaadin-crud-grid.html
src/vaadin-crud-include-mixin.html
src/vaadin-crud.html

Fixes #104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/136)

Extract common code from grid and form classes

---

bower.json
demo/crud-advanced-demos.html
demo/crud-basic-demos.html
demo/crud-custom-demos.html
demo/crud-data-demos.html
demo/crud-i18n-demos.html
demo/crud-theme-demos.html
demo/data.js
demo/index-material.html
demo/index.html

Fixes #126
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/140)

Remove iron-ajax from demos

---

demo/index-material.html
theme/vaadin-dialog-layout-overlay-styles.html

Fixes #142
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/143)

Fix dialog height in small viewport

---

test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/152)

Make tests green again

---

README.md
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/154)

Add `npm start` script

---

src/vaadin-crud.html
test/crud-test.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/157)

Don't modify original item if default is prevented on save

---

bower.json
demo/crud-basic-demos.html
src/vaadin-crud.html
src/vaadin-dialog-layout.html
test/crud-test.html
theme/lumo/vaadin-crud-styles.html
theme/material/vaadin-crud-styles.html

- Accepts one value: `bottom`
- _empty string (default) works as overlay_
- Add demo showing the new feature
- Theme updated
Fixes #167
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/169)

Add editor-position property

---

src/vaadin-crud.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/172)

Add reflectToAttribute to editorPosition

---

src/vaadin-crud.html
test/crud-test.html

Resolves #176 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/vaadin-crud/178)

Highlight edited item by setting it selected in the grid

---

bower.json
src/vaadin-crud-edit-column.html
src/vaadin-crud-edit.html

fix: split elements into separate files

---

@types/interfaces.d.ts
bower.json

Related with vaadin/vaadin-grid#1764

fix: make CrudItem compatible with interfaces

---

src/vaadin-crud.html
test/crud-test.html

Add handling of editor canceling via Esc or click outside (#201)

---

package.json
src/vaadin-crud.html
test/crud-test.html

cherry-pick of vaadin/web-components#3831 and vaadin/web-components#3832
related-to vaadin/web-components#3773

chore: Add cvdlName metadata

---

bower.json
package-lock-p3.json

Updated the dependency version.
- Version bump

chore: update vaadin-text-field and vaadin-grid versions
